# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sdc}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristan Krispy Uccello"]
  s.date = %q{2010-07-01}
  s.description = %q{This is an api wrapper that makes using Shopping.com's API a lot easer}
  s.email = %q{kuccello@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    ".bundle/config",
     ".document",
     ".gitignore",
     ".idea/encodings.xml",
     ".idea/misc.xml",
     ".idea/modules.xml",
     ".idea/sdc.iml",
     ".idea/vcs.xml",
     "Gemfile",
     "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/sdc.rb",
     "lib/sdc/api_exception.rb",
     "lib/sdc/attribute.rb",
     "lib/sdc/attribute_selection.rb",
     "lib/sdc/attribute_value.rb",
     "lib/sdc/category.rb",
     "lib/sdc/category_selection.rb",
     "lib/sdc/category_tree_response.rb",
     "lib/sdc/client.rb",
     "lib/sdc/client_tracking.rb",
     "lib/sdc/consumer_review.rb",
     "lib/sdc/dynamic_navigation_history.rb",
     "lib/sdc/feature.rb",
     "lib/sdc/feature_group.rb",
     "lib/sdc/feature_rating.rb",
     "lib/sdc/general_search_response.rb",
     "lib/sdc/generic_response.rb",
     "lib/sdc/image.rb",
     "lib/sdc/keyword_search.rb",
     "lib/sdc/offer.rb",
     "lib/sdc/offer_selection.rb",
     "lib/sdc/product.rb",
     "lib/sdc/product_selection.rb",
     "lib/sdc/search_history.rb",
     "lib/sdc/server_detail.rb",
     "lib/sdc/store.rb",
     "sdc.gemspec",
     "spec/sdc_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "test/sdc_test.rb"
  ]
  s.homepage = %q{http://github.com/kuccello/sdc}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Wrapper for Shopping.com REST API}
  s.test_files = [
    "spec/sdc_spec.rb",
     "spec/spec_helper.rb",
     "test/sdc_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

